# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mullerHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='is_preview',
            field=models.BooleanField(default=True),
        ),
    ]
